# Generated by Django 4.1 on 2022-08-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m'),
        ),
    ]
